youtuberList = [
    ("PewDiePie", "https://www.youtube.com/user/PewDiePie"),
    ("MrBeast", "https://www.youtube.com/user/MrBeast6000"),
    ("Dude Perfect", "https://www.youtube.com/user/corycotton"),
    ("Markiplier", "https://www.youtube.com/user/markiplierGAME"),
    ("DanTDM", "https://www.youtube.com/user/TheDiamondMinecart"),
    ("VanossGaming", "https://www.youtube.com/user/VanossGaming"),
    ("Jacksepticeye", "https://www.youtube.com/user/jacksepticeye"),
    ("Jelly", "https://www.youtube.com/user/JellyYT"),
    ("KSI", "https://www.youtube.com/user/KSIOlajidebt"),
    ("SSSniperWolf", "https://www.youtube.com/user/SSSniperWolf"),
    ("Rhett & Link", "https://www.youtube.com/user/rhettandlink2"),
    ("Smosh", "https://www.youtube.com/user/smosh"),
    ("LazarBeam", "https://www.youtube.com/channel/UCw1SQ6QRRtfAhrN_cjkrOgA"),
    ("Ninja", "https://www.youtube.com/user/NinjasHyper"),
    ("Zoella", "https://www.youtube.com/user/zoella280390"),
    ("T-Series", "https://www.youtube.com/user/tseries"),
    ("Liza Koshy", "https://www.youtube.com/channel/UCxSz6JVYmzVhtkraHWZC7HQ"),
    ("Collins Key", "https://www.youtube.com/user/CollinsKey"),
    ("Rclbeauty101", "https://www.youtube.com/user/Rclbeauty101"),
    ("Superwoman", "https://www.youtube.com/user/IISuperwomanII"),
    ("Rosanna Pansino", "https://www.youtube.com/user/RosannaPansino"),
    ("The Slow Mo Guys", "https://www.youtube.com/user/theslowmoguys"),
    ("FBE", "https://www.youtube.com/user/TheFineBros"),
    ("Epic Meal Time", "https://www.youtube.com/user/EpicMealTime"),
    ("JennaMarbles", "https://www.youtube.com/user/JennaMarbles"),
    ("Michelle Phan", "https://www.youtube.com/user/MichellePhan"),
    ("Shane Dawson", "https://www.youtube.com/user/shane"),
    ("Joey Graceffa", "https://www.youtube.com/user/JoeyGraceffa"),
    ("Roman Atwood", "https://www.youtube.com/user/RomanAtwood"),
    ("Unbox Therapy", "https://www.youtube.com/user/unboxtherapy"),
    ("Good Mythical Morning", "https://www.youtube.com/user/rhettandlink2"),
    ("Miranda Sings", "https://www.youtube.com/user/mirandasings08"),
    ("The Game Theorists", "https://www.youtube.com/user/MatthewPatrick13"),
    ("Nigahiga", "https://www.youtube.com/user/nigahiga"),
    ("Tati", "https://www.youtube.com/user/GlamLifeGuru"),
    ("Safiya Nygaard", "https://www.youtube.com/channel/UCbAwSkqJ1W_Eg7wr3cp5BUA"),
    ("Tom Scott", "https://www.youtube.com/user/enyay"),
    ("Marques Brownlee", "https://www.youtube.com/user/marquesbrownlee"),
    ("Casey Neistat", "https://www.youtube.com/user/caseyneistat"),
    ("Vsauce", "https://www.youtube.com/user/Vsauce"),
    ("Philip DeFranco", "https://www.youtube.com/user/sxephil"),
    ("Jenn Im", "https://www.youtube.com/user/clothesencounters"),
    ("Grace Helbig", "https://www.youtube.com/user/graciehinabox"),
    ("Joe Sugg", "https://www.youtube.com/user/ThatcherJoe"),
    ("Alfie Deyes", "https://www.youtube.com/user/PointlessBlogTv"),
    ("Ingrid Nilsen", "https://www.youtube.com/user/missglamorazzi"),
    ("Cryaotic", "https://www.youtube.com/user/ChaoticMonki"),
    ("The Try Guys", "https://www.youtube.com/channel/UCpi8TJfiA4lKGkaXs__YdBA"),
    ("MatPat", "https://www.youtube.com/user/MatthewPatrick13"),
    ("Brave Wilderness", "https://www.youtube.com/user/BreakingTrail"),
    ("iJustine", "https://www.youtube.com/user/ijustine"),
    ("Bethany Mota", "https://www.youtube.com/user/Macbarbie07"),
    ("AsapSCIENCE", "https://www.youtube.com/user/AsapSCIENCE"),
    ("ThreadBanger", "https://www.youtube.com/user/ThreadBanger"),
]